// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ColumnsSetup: typeof import('./src/components/ProTable/components/ColumnsSetup/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FullScreenIcon: typeof import('./src/components/FullScreenIcon/index.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Pagination: typeof import('./src/components/ProTable/components/Pagination/index.vue')['default']
    ProTable: typeof import('./src/components/ProTable/index.vue')['default']
    Table: typeof import('./src/components/ProTable/components/TableList/Table.vue')['default']
    TableList: typeof import('./src/components/ProTable/components/TableList/index.vue')['default']
    Toolbar: typeof import('./src/components/ProTable/components/Toolbar/index.vue')['default']
  }
}

export { }
